### ISSUE TITLE
Trailers Directory

### ISSUE THREAD

**Issue by Protektor-Desura** [RandomNinjaAtk/docker-amtd#10]
There is some kind of problem with the creation of trailers directories. The script keeps creating them without the execute bit under docker so you can't access it and it can't actually put trailers in there.
-e FilePermissions = 644
-e FolderPermissions = 755

I tried setting those environment variables and it doesn't seem to help at all.

**Comment by RandomNinjaAtk** [comment]
Not aware of any problems, could be a problem with how you have Radarr configured. It sounds like Radarr has locked down the directory too much for the script to be able to access them. 

Also feel free to join the discord. My guess is it's a problem with your Radarr configuration...

**Comment by RandomNinjaAtk** [comment]
Just a thought... Also as of now, there is no folder permissions setting... Probably something that needs to be added though, right now I think it uses the FilePermissions setting for that, but still chown's them to the correct puid/pgid

**Comment by Protektor-Desura** [comment]
The problem isn't permissions for the directory, because it does create the "Trailers" directory in the movie folder/directory. The problem is the permissions is uses when it create the folder "Trailers" which it is using the same permissions as the FilePermissions which does NOT include the execute flag because you don't execute videos, you just read them. There needs to be different permissions from FilePermissions, like FolderPermissions. The issue is it is creating the "Trailers" directory using FilePermissions which a problem.

**Comment by Protektor-Desura** [comment]
What is your discord channel/server since I am on discord.

**Comment by RandomNinjaAtk** [comment]
@Protektor-Desura Images should be building, once there complete. Update your container and configure the new settings and see if that fixes it. It won't modify anything for existing folders/files. You may need to clean that up manually.

**Comment by Protektor-Desura** [comment]
Works perfectly for me now. I did have to remove all trailers directories because of wrong permissions, but it is working now for me. Thanks.
