### ISSUE TITLE
Great initiative. error fixed output name but more than one file to download

### ISSUE THREAD

**Issue by michpas** [RandomNinjaAtk/docker-amtd#11]
Great tool. Keen to test this out.
When I installed the docker on my synology I see that it connects with Radarr, creates the required sub-folders in each movie-directory; but they are all empty.

In the log I see a couple of error messages:
**Connect to Radar**
   ERROR: Cannot communicate with Radarr, most likely a....
   ERROR: Invalid API Key: 9135b3xxxxxxxxx661c94cef6
But it still connects correct to Radarr fine. It reads it's media folder and all movies. Not sure why this error.

I set the permissions of folder and file to 777 to ease access

youtube-dl: /config/cookies/cookies.txt found!; which is ok.

But then I get for every download the following error:
ERROR: fixed output name but more than one file to download

Eventually the folders do get created within each movie folder, but they stay empty.

Any ideas how to solve this?
Thanks

Edit:
--- Maybe it has something to do with?
https://www.reddit.com/r/youtubedl/comments/cg0hwk/fixed_output_name_but_more_than_one_file_to/

**Comment by RandomNinjaAtk** [comment]
Typically if your getting that error, the script should never run because it should exit... 

Are you on v2 or v3?

 I've only ever used v3, so if your on v2, maybe there is a incompatibility...

**Comment by michpas** [comment]
yeah. still running (stable) v2. :-)

**Comment by RandomNinjaAtk** [comment]
Maybe setup a test instance for V3 and see if you can get it working... I'm not sure I'd take the time to fix it at all for V2 if that is the reason... 

PR welcome if you want to write a fix to make it compatible with both if that is the case...

**Comment by michpas** [comment]
yeah. let me try to create a V3 instance and do some testing on that. Will let you know

**Comment by michpas** [comment]
Hi RandomNinjaAtk.
I installed Radarr V3. Looks pretty nice :-)
Ran the same amtd on the new Radarr version.
Good news: no connection radarr error message. However I still get the same problem that the extra videos are not downloaded.
Amtd creates the sub-folder in the movie folder, but there is no storage of the extra videos.
The Message in the log ERROR: fixed output name but more than one file to download

I don't what is causing the problem, but google seems to state something with the parameters.
https://www.reddit.com/r/youtubedl/comments/cg0hwk/fixed_output_name_but_more_than_one_file_to/

**Comment by RandomNinjaAtk** [comment]
You may need to pastebin the script log or hop on discord and post it some way. Just not enough detail to really know whats going on...

**Comment by michpas** [comment]
Thanks to the great support of RandomNinjaAtk, it is solved. Sharing the solution.
For users with a synology NAS that are using the standard Synology docker UI screens, the 

value of 
-e videoformat="--format bestvideo[vcodec*=avc1]+bestaudio"
should be entered as without the "'s 
-e videoformat=--format bestvideo[vcodec*=avc1]+bestaudio

**Comment by kushfest** [comment]
FYI...I had to make this change when using the docker-compose example in Portainer.
