### ISSUE TITLE
Suggestion. Dl only one trailer and avoid subfolders

### ISSUE THREAD

**Issue by michpas** [RandomNinjaAtk/docker-amtd#12]
To have an option/selection that only downloads 1 trailer and put the file in the same folder as the movie with [name]-trailer.mkv

Advantages:
1. plex, jellyfin only show 1 trailer icon.there is no selection option. Having 1 file keeps it clean and a avoind unnessesary dl of multiple trailers
2. This method also works in jellyfin as it doesnt support trailers in subfolders.

This will also make it easier for amtd to scan for excisting trailer files and simpky skip

**Comment by RandomNinjaAtk** [comment]
Done
