### ISSUE TITLE
Suggestion Temp working files in config/temp folder

### ISSUE THREAD

**Issue by michpas** [RandomNinjaAtk/docker-amtd#13]
When dl and procesding, all dl (temp) files are directly stored within the movie directory.
For me, ths triggers automatic scan from other apps as tdarr for processing.

Best would be to keep working files in /config/cache abd only move to final location when trailer file is final.

**Comment by RandomNinjaAtk** [comment]
Done

**Comment by michpas** [comment]
Wow. That is a fast turn around. I'll dl a new docker file and retest.
Thanks man! great work
very impressive,
