### ISSUE TITLE
Ignore movies already processed

### ISSUE THREAD

**Issue by crypto-vault** [RandomNinjaAtk/docker-amtd#14]
The script takes around 15% cpu in a 8 core i7 9700 and does this every hour for 15 minutes (depends on library size).

If you have big part of your library in archive where movie is no longer monitored in Radarr but it's still there the script still takes 15% of cpu just to find out "Movie Path does not exist".

A few options here could be:

1) Find out why it takes so much cpu just to find out movie path does not exist.
2) Create a cache of movies already processed and ignore them on the next runs (with a variable like ignoreprocessed for example).
3) Ignore movies that are unmonitored in Radarr (maybe not recommended). 
4) Have option to change cron to run daily instead of hourly (or any other timeframe).

**Comment by RandomNinjaAtk** [comment]
So few things...

1. If you could look into that, that would be helpful
2. It already does this using cache, still has perform api hit to radarr... (might be able to re-arrange processes to reduce it some...)
3. This may be possible, but not really sure why its needed unless you don't want trailers at all for that particular item
4. You can disable auto-start and create a script to execute the script manually via a cron job from the host ....

Edit: 

Upon further inspection (for 2..), the first thing the script does is check the cache if the Movie has been marked completed. So the only process before that, is the call to radarr to get the movie list, and configuration verification, not sure anything more can be done in that regards.... to make it any faster... 

For reference: https://github.com/RandomNinjaAtk/docker-amtd/blob/d9ec3f835317cf00f5edb05f9d951f92a0865c47/root/scripts/download.bash#L153-L156

**Comment by RandomNinjaAtk** [comment]
Updated the script to try to make it fast as possible. The reason verifying movie paths might take so long, is because it performs a disk check.

So if your disks are sleeping, they would have to spin up just for the script to perform a simple check if the folder exists....

Just a thought.... Give the update a try when it hits...

Relevant changes: https://github.com/RandomNinjaAtk/docker-amtd/commit/91f3834b46eb9be40f896c24a679db88944b88c1

**Comment by RandomNinjaAtk** [comment]
I think this last change will address my last statement: https://github.com/RandomNinjaAtk/docker-amtd/commit/12453fdf5e436cef3b79e15c287249423d5762fa

Found something that could be used in Radarr's API. So I don't think I could make it any faster at this point....

Please give the latest updates a try...

**Comment by RandomNinjaAtk** [comment]
The latest changes should allow adjusting sleep period between script runs....

I think this addresses everything as much as possible, give it a try...

**Comment by crypto-vault** [comment]
Thanks, I was going to debug to see if caching movie dir would speed up things, so that it didn't have to jq so much, but your changes with hasFile=true improved things. It still takes 15% from cpu but now it's only running for a fraction of the movie list so it takes less time to run. Also took advantage of SCRIPTINTERVAL to make interval longer between runs.

**Comment by RandomNinjaAtk** [comment]
Okay, think this is complete now...
