### ISSUE TITLE
new feature: language

### ISSUE THREAD

**Issue by michpas** [RandomNinjaAtk/docker-amtd#16]
When downloading trailers for kids movies (mostly animation) , I would like to get the trailers in native language

I tried:
-e subtitlelanguage=nl
This resulted in 50% of the movies getting a trailer downloaded
Of this, the majority was dutch spoken (which is correct)
and a few in english with dutch subtitle. (which is also ok - for interim)
But it also didn't download trailers for the other 50% the movies
The error in the log:  27 of 40 :: xxxxx :: ERROR: No Trailer ID Found (xxxxxx), Skipping...

As it would be nice to have a trailer, so if my preferred language is not available, take English (or any)
So I tried:
-e subtitlelanguage=nl,en
This resulted in a few more trailers to be downloaded, but not all. Some movies where still skipped.

Then I removed the filter:
-e subtitlelanguage=nl,en
That resulted in all movies getting a trailer downloaded.

Question:
Would it be possible when scanning for the trailer to try to download the most preferred one to less preferred?
For me that would be for example with NL spoken or nl subtitled or the word NL in the trailer and officiele (official)
This would require the 'search' to be a bit smarter and when there are multiple results to pick the best one.

Happy to analyze the results and see what logic works best.

Thanks for your views/thoughts.

**Comment by RandomNinjaAtk** [comment]
Script only handles a single language. That option does work for youtube-dl but its also used in this case for themoviedb filtering. So adding 2 like that probably breaks it....

This script is really only designed to handle one single primary language. 

So if your primary is "nl" you should set that to only nl

Also note, this script does not use any kind of searching.


EDIT: You could run the script multiple times, changing the language setting to get the results your looking for... That may be the best way to handle it.
