### ISSUE TITLE
improvement Suggestion: Language tag. multiple values

### ISSUE THREAD

**Issue by michpas** [RandomNinjaAtk/docker-amtd#17]
The subtitlelanguage tag works good; however it only seems to accept the first value.
In my situation I would prefer a local subtitle if available (lets say nl);
but this gives only around 50% of the hits as simply not all trailers are available matching this value.
For the others, where the prefered subtitle is not available, it could default back to english. Its more important to have a trailer and not to have one at all :-)

So, I guess I'm looking for 2 runs. First run is using the local subtitlelanguage (nl) and 2nd run to query and download the english version if there was no found.

I could configure/run 2 docker instances; but after a reset/reboot they would both start at the same time and I would prefer a search for the local version first

Would it be possible for the script to run for all languages included? (eg. value = nl,en)
First complete run for subtitlelanguage='dl' and second full run for subtitlelanguage='en')?

This would really help to ensure there is always first an attempt for a local version afterwhich not found the english is picked up.

Thanks for your consideration

**Comment by RandomNinjaAtk** [comment]
This should be implemented, give it a whirl and let me know...

**Comment by michpas** [comment]
Thanks for the quick turn around.
I noticed in the instructions you added -e languages, besided the subtitle languages.

The following settings are working really well for me
-e LANGUAGES=nl,en 
-e subtitlelanguage=nl

This dl's first any nl-trailer if registered in tmbd and if not, it takes the en version. Perfect result ! 

Thank you
