### ISSUE TITLE
[REQ] Sonarr support for TV shows trailers

### ISSUE THREAD

**Issue by crypto-vault** [RandomNinjaAtk/docker-amtd#18]
Are you planning on adding Sonarr support for TV shows trailers?

**Comment by RandomNinjaAtk** [comment]
Didn't know that was a thing? Any good info on it?

**Comment by crypto-vault** [comment]
Info on Sonarr or on how to collect tv shows trailer info?

For Sonarr API it's here, similar to Radarr API:
https://github.com/Sonarr/Sonarr/wiki/API

For info on collecting trailers for TV shows you can check the code of TinyMediaManager but I guess your code already covers it:
https://www.tinymediamanager.org/

**Comment by ycodryn** [comment]
At first I thought that this would be a nice feature but thinking deeper is just enough for movies. Who is downloading entire tv shows not knowing what it is about? For movies yes sure but for tv shows is not practical, usually there is a trailer for every season so this will complicate things. My opinion, leave it simple.

**Comment by emopinata** [comment]
> At first I thought that this would be a nice feature but thinking deeper is just enough for movies. Who is downloading entire tv shows not knowing what it is about? For movies yes sure but for tv shows is not practical, usually there is a trailer for every season so this will complicate things. My opinion, leave it simple.

Plex has trailers for tv shows, but so far I've only seen them exposed through the web client and the last time I tried to manually add one I couldn't get it to work. However, should that be solved, I think it would be great to have show and season trailers, since not all users would know what a show is about.

**Comment by huteri** [comment]
I have modified version here for sonarr https://github.com/huteri/docker-amtd

Thanks @RandomNinjaAtk for a great script,

**Comment by RandomNinjaAtk** [comment]
> I have modified version here for sonarr https://github.com/huteri/docker-amtd
> 
> Thanks @RandomNinjaAtk for a great script,

Nice work, but it would probably be a good idea to rename it to avoid confusion. docker-attd, maybe...?

**Comment by snickers2k** [comment]
can you please merge the both together maybe? Cause i'm guessing running both together will trigger the youtube limits?
thanks

attd is sadly not working for me, while amtd is working great

update: okay, got it. had to set up every single sonarr folder in attd. something not needed for amtd. now it's working.

**Comment by dannymichel** [comment]
> https://github.com/huteri/docker-amtd

is this working and still being maintained?

**Comment by RandomNinjaAtk** [comment]
I plan to revisit this when I develop sonarr-extended, which will be simliar to radarr-extended (https://github.com/RandomNinjaAtk/docker-radarr-extended)

This project is being deprecated and replaced by radarr-extended
