### ISSUE TITLE
SINGLETRAILER set to true but attempting to download multiples

### ISSUE THREAD

**Issue by edsai** [RandomNinjaAtk/docker-amtd#19]
For some reason when I run the container with SINGLETRAILER set to true, it attempts to download multiple trailers and yt-downloader throws an error of "ERROR: fixed output name but more than one file to download".

Here's a snippet from the log:

############################################ CONFIGURATION VERIFICATION
AMTD Script Autostart: ENABLED
AMTD Script Interval: 1h
Radarr v0.2 API: Connection Valid, version: 3.0.0.3129
Radarr: Verifying Movie Directory Access:
Radarr: Root Media Folder Found: /media/Movies
youtube-dl: Checking for cookies.txt
youtube-dl: /config/cookies/cookies.txt found!
Radarr Extras Selection: trailers
Radarr Extras Audio Languages: en (first one found is used)
Radarr Extras Format Set To: "--format bestvideo[vcodec*=avc1]+bestaudio"
Radarr Extras Subtitle Language: en
Radarr Extras File Permissions: 644
Radarr Extras Foldder Permissions: 755
Radarr Single Trailer: ENABLED
Radarr Use Extras Folders: DISABLED
############################################ DOWNLOADING TRAILERS
1 of 3823 :: 10 Cloverfield Lane
1 of 3823 :: 10 Cloverfield Lane :: Searching for "en" extras...
1 of 3823 :: 10 Cloverfield Lane :: 1 Extras Found!
1 of 3823 :: 10 Cloverfield Lane :: 1 of 1 :: Trailer :: Official Trailer
1 of 3823 :: 10 Cloverfield Lane :: 1 of 1 :: trailer :: Official Trailer :: Sending Trailer link to youtube-dl...
=======================START YOUTUBE-DL=========================
ERROR: fixed output name but more than one file to download
========================STOP YOUTUBE-DL=========================
1 of 3823 :: 10 Cloverfield Lane :: 1 of 1 :: trailer :: Official Trailer :: TRAILER DOWNLOAD :: ERROR :: Skipping...
1 of 3823 :: 10 Cloverfield Lane :: 0 Extras Downloaded!
2 of 3823 :: Twelve Monkeys
2 of 3823 :: Twelve Monkeys :: Searching for "en" extras...
2 of 3823 :: Twelve Monkeys :: 1 Extras Found!
2 of 3823 :: Twelve Monkeys :: 1 of 1 :: Trailer :: 12 Monkeys - Trailer HD (A Re-Creation)
2 of 3823 :: Twelve Monkeys :: 1 of 1 :: trailer :: 12 Monkeys - Trailer HD (A Re-Creation) :: Sending Trailer link to youtube-dl...
=======================START YOUTUBE-DL=========================
ERROR: fixed output name but more than one file to download
========================STOP YOUTUBE-DL=========================
2 of 3823 :: Twelve Monkeys :: 1 of 1 :: trailer :: 12 Monkeys - Trailer HD (A Re-Creation) :: TRAILER DOWNLOAD :: ERROR :: Skipping...
2 of 3823 :: Twelve Monkeys :: 0 Extras Downloaded!
3 of 3823 :: 12 Years a Slave
3 of 3823 :: 12 Years a Slave :: Searching for "en" extras...
3 of 3823 :: 12 Years a Slave :: 1 Extras Found!
3 of 3823 :: 12 Years a Slave :: 1 of 1 :: Trailer :: 12 YEARS A SLAVE - Official Trailer (HD)
3 of 3823 :: 12 Years a Slave :: 1 of 1 :: trailer :: 12 YEARS A SLAVE - Official Trailer (HD) :: Sending Trailer link to youtube-dl...
=======================START YOUTUBE-DL=========================
ERROR: fixed output name but more than one file to download
========================STOP YOUTUBE-DL=========================
3 of 3823 :: 12 Years a Slave :: 1 of 1 :: trailer :: 12 YEARS A SLAVE - Official Trailer (HD) :: TRAILER DOWNLOAD :: ERROR :: Skipping...
3 of 3823 :: 12 Years a Slave :: 0 Extras Downloaded!
4 of 3823 :: 127 Hours
4 of 3823 :: 127 Hours :: Searching for "en" extras...
4 of 3823 :: 127 Hours :: 2 Extras Found!
4 of 3823 :: 127 Hours :: 1 of 2 :: Trailer :: 127 HOURS - Full Length Official Trailer HD
4 of 3823 :: 127 Hours :: 1 of 2 :: trailer :: 127 HOURS - Full Length Official Trailer HD :: Sending Trailer link to youtube-dl...
=======================START YOUTUBE-DL=========================
ERROR: fixed output name but more than one file to download
========================STOP YOUTUBE-DL=========================
4 of 3823 :: 127 Hours :: 1 of 2 :: trailer :: 127 HOURS - Full Length Official Trailer HD :: TRAILER DOWNLOAD :: ERROR :: Skipping...
4 of 3823 :: 127 Hours :: 0 Extras Downloaded!
5 of 3823 :: 13 Hours: The Secret Soldiers of Benghazi
5 of 3823 :: 13 Hours: The Secret Soldiers of Benghazi :: Searching for "en" extras...
5 of 3823 :: 13 Hours: The Secret Soldiers of Benghazi :: 2 Extras Found!

**Comment by RandomNinjaAtk** [comment]
Your format parameter is wrong in your docker config. Remove the double quotes "

**Comment by edsai** [comment]
Thanks for the help. Note that note that in the amtd README.md, the docker-compose example does indeed have quotes. There's also a trailing slash next to languages that shouldn't be there as well. Appreciate all the hard work!

**Comment by RandomNinjaAtk** [comment]
I'm guessing this is resolved then....
