### ISSUE TITLE
Unable to find media

### ISSUE THREAD

**Issue by natcoso9955** [RandomNinjaAtk/docker-amtd#2]
I have configured an additional volume which is setup the same as Radarr (/downloads/media/ -> /mnt/user/Media/Movies) but when i start the container im getting the below error.

ERROR: Root Not Found, please verify you have the right volume configured, expecting path:
ERROR: /downloads/Movies

**Comment by RandomNinjaAtk** [comment]
If I'm reading the error correctly, your volumes don't match your Radarr container and that is why your getting the error.

Looks like in Radarr under media folders, you have a root folder added as "/downloads/Movies"

So to resolve the error, you most likely need to add a volume that matches and begins with:  /downloads

Hope that helps...

**Comment by natcoso9955** [comment]
AMTD
![image](https://user-images.githubusercontent.com/11192857/89477690-13e0f980-d7cd-11ea-9eb9-881a8a4b45d6.png)
Radarr
![image](https://user-images.githubusercontent.com/11192857/89477746-3541e580-d7cd-11ea-8811-e7ba673b03db.png)

Im guessing my AMTD one is wrong, but i didnt really understand what to set it with from:

-v /change/me/to/match/radarr | Configure this volume to match your Radarr Radarr's volume mappings associated with Radarr's Library Root Folder settings
-- | --

Doesnt really say what the AMTD container volume should be.
Please advise.

**Comment by RandomNinjaAtk** [comment]
You want them to be the same.. If you make the volumes exactly the same, it will just work.

So replicate the volume mappings from Radarr into this container and it should just work.

Because your image clearly shows they are both completely different, which is why your getting that error...

**Comment by natcoso9955** [comment]
updated, same error.
weirdly, its the exact same error, referencing /downloads still.
I even removed the docker image and set it from the beginning.

AMTD
![image](https://user-images.githubusercontent.com/11192857/89478447-2825f600-d7cf-11ea-8ae9-7d162bba2456.png)

Radarr
![image](https://user-images.githubusercontent.com/11192857/89478458-3116c780-d7cf-11ea-88b6-48038d4a1350.png)

**Comment by RandomNinjaAtk** [comment]
Also add the /downloads which is also on your Radarr and it should work. You must have a /downloads root path configured in your Radarr library, and that's why it's looking for it.

Also if you look in your Radarr Media folder settings, you will probably see that you have it configured. If its not there, you must have a movie in your library mapped to that path...

**Comment by natcoso9955** [comment]
That is very weird, i literally dont use the /downloads folder configured in radarr but that worked.

**Comment by RandomNinjaAtk** [comment]
Glad you were able to resolve it, all I can tell you is that you must have it configured somewhere in Radarr app, or it wouldn't be looking for it.
