### ISSUE TITLE
HTTP Error 429

### ISSUE THREAD

**Issue by ookla-ariel-ride** [RandomNinjaAtk/docker-amtd#22]
Starting to get 429 errors.  Any suggestion on how to avoid/mitigate?  I have a large movie collection (20K+), have been running AMTD for a while and just noticed these errors in the log.

```
=======================START YOUTUBE-DL=========================
[youtube] xxxxxxxxxxx: Downloading webpage

ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many 
Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-
dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

========================STOP YOUTUBE-DL=========================
```

**Comment by RandomNinjaAtk** [comment]
You need to use cookies.txt
https://github.com/RandomNinjaAtk/docker-amtd#directories

Its a YOUTUBE-DL feature, see there documentation for further assistance

**Comment by ookla-ariel-ride** [comment]
using this extension in Chrome helps with creating the cookies.txt file in proper format.  https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg

**Comment by tehniemer** [comment]
> using this extension in Chrome helps with creating the cookies.txt file in proper format. https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg

This link leads to a 404, I ended up finding and using the EditThisCookie extension, it's also able to export cookies in the proper netscape format. 
https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg
