### ISSUE TITLE
High CPU usage when script is running

### ISSUE THREAD

**Issue by tehniemer** [RandomNinjaAtk/docker-amtd#24]
I've noticed that this script seems very processor intensive, is this much usage normal?

![image](https://user-images.githubusercontent.com/11021632/105875835-e890d780-5fc3-11eb-841a-dec89b58e62d.png)

**Comment by RandomNinjaAtk** [comment]
Nothing to be done about this, the script uses software and the software can process intensive. If you find a better way, PR is welcome.
