### ISSUE TITLE
[REQ] - Refresh Metadata in Plex

### ISSUE THREAD

**Issue by blackthroat** [RandomNinjaAtk/docker-amtd#26]
As Radarr moves/copies the downloaded files to my media directory and Plex has "Scan my library automatically" enabled, trailers downloaded and put in place by AMTD (triggered to run every 1 hour by default) will not be recognized by Plex unless you manually trigger a metadata refresh, or wait until the Plex Scheduled Task "Refresh local metadata every three days" runs. It would be great if the trailers were automatically ready to view through Plex right away. 

I inspected the network activity in Chrome when clicking Refresh Metadata for a particular movie through Plex and it returned the following:
`https://172-16-0-15.[REDACTED].plex.direct:32400/library/metadata/1106/refresh`

Would AMTD would have access to that metadata number (1106) for the movie, perhaps from Radarr? That way metadata could be refreshed for that specific item.

If not, Refresh All Metadata for the library would suffice for my needs, although I understand depending on the size of a user's library, this could cause performance issues if it is constantly being ran.

`http://[PMS_IP_ADDRESS]:32400/library/sections/29/refresh?force=1&X-Plex-Token=YourTokenGoesHere`

Perhaps a new optional environment variable like `PlexMetadataRefresh`, which runs directly after the `SCRIPTINTERVAL`, and only if new trailers are downloaded in that run, that all library metadata would be refreshed with a simple HTTP POST/PUT?

https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
https://support.plex.tv/articles/201638786-plex-media-server-url-commands/
https://support.plex.tv/articles/200289306-scanning-vs-refreshing-a-library/

**Comment by vladola** [comment]
+1 on this, it would be really helpful.

**Comment by RandomNinjaAtk** [comment]
@blackthroat 
The only way I could foresee making this work would be to trigger a Full Metadata Refresh on all libraries matching the type "movie"... 

It's not really a great solution though, but shouldn't be too hard to implement if that is what you want...?

**Comment by blackthroat** [comment]
@vladola Any input on this from you?

I'm not sure I have a need for this request anymore as a I believe I was experiencing a bug with Plex Media Server that has since been fixed in the past few weeks with a new release. I also have since purchased Plex Pass, but I don't believe that is relevant in this case and that pertains to "Play trailers for new and upcoming theater and Blu-ray releases."

To test this, I turned off the amtd container and then added something to my Plex library. After browsing to the movie, I confirmed there is no Play Trailer icon:

![image](https://user-images.githubusercontent.com/25038086/123968448-d6ed9a80-d97c-11eb-892c-ab70e3d78abb.png)

After turning the amtd container back on and the script ran, the Play Trailer icon was present:

![image](https://user-images.githubusercontent.com/25038086/123969897-44e69180-d97e-11eb-8753-f8170f2f1824.png)

There was no need (as there was in the past) to Refresh Metadata on the single movie itself or Refresh All Metadata on the entire library.

I then deleted the Trailers folder, navigated away from the movie and then back into it, and as expected, the Play Trailer icon was gone. I then removed the associated file for that specific movie from `/config/cache`, ran `bash /config/scripts/download.bash`, navigated away from the movie and then back into it, and the Play Trailer icon was present.

My guess is the "Scan my library automatically" (Your library will be updated automatically when changes to library folders are detected), which is found in PMS: Settings > Library, is now picking up the addition of the Trailers folder and trailer movie file, which it wasn't doing before.

**Comment by vladola** [comment]
> My guess is the "Scan my library automatically" (Your library will be updated automatically when changes to library folders are detected), which is found in PMS: Settings > Library, is now picking up the addition of the Trailers folder and trailer movie file, which it wasn't doing before.

This. Seems Plex does this automatically if that option is enabled. I think this issue can be closed.
