### ISSUE TITLE
Support for Radarr V4 API

### ISSUE THREAD

**Issue by ookla-ariel-ride** [RandomNinjaAtk/docker-amtd#29]
Radarr V3 API is deprecated, see errors below:

> ############################################ Automated Movie Trailer Downloader (AMTD)                             ││   ############################################ SCRIPT VERSION 1.2.1                                                  ││   ############################################ DOCKER VERSION 1.0.6                                                  ││   ############################################ CONFIGURATION VERIFICATION                                            ││   AMTD Script Autostart: ENABLED                                                                                     ││   AMTD Script Interval: 1h                                                                                           ││   Radarr v3 API: Connection Valid, version: 4.0.0.5093                                                               ││   jq: error (at <stdin>:3): Cannot index string with string "hasFile"                                                ││   jq: error (at <stdin>:3): Cannot index string with string "hasFile"                                                ││   Radarr: Verifying Movie Directory Access:                                                                          ││   youtube-dl: Checking for cookies.txt                                                                               ││   youtube-dl: /config/cookies/cookies.txt found!                                                                     ││   Radarr Extras Selection: all                                                                                       ││   Radarr Extras Audio Languages: en (first one found is used)                                                        ││   Radarr Extras Format Set To: --format bestvideo[vcodec*=avc1]+bestaudio                                            ││   Radarr Extras Subtitle Language: en                                                                                ││   Radarr Extras File Permissions: 644                                                                                ││   Radarr Extras Foldder Permissions: 755                                                                             ││   Radarr Single Trailer: DISABLED                                                                                    ││   Radarr Use Extras Folders: ENABLED                                                                                 ││   ############################################ DOWNLOADING TRAILERS                                                  ││   find: ‘’: No such file or directory                                                                                ││   ############################################ 0 TRAILERS DOWNLOADED                                                 │

**Comment by RandomNinjaAtk** [comment]
This should be fixed in the latest...? Give it a try...

**Comment by RandomNinjaAtk** [comment]
no response...
