### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by TR7Mike** [RandomNinjaAtk/docker-amtd#32]
I have a parallel docker container to radarr on the same Proxmox linux host. I've used the same paths and it reads the movies. But I'm getting a bunch of errors when it comes to downloading the trailers. I do also see AMTD skip due to existing trailers, which is fine. 

Here is the excerpt from the log output and the Radarr and AMTD compose files are below.

Any thoughts on what's afoot?
Edit: Apologies, but I can't get the inserted code (log) snippits to look right

`10 of 1040 :: Die Hard :: 1 of 3 :: trailer :: Die Hard (1988) Trailer #1 | Movieclips Classic Trailers :: TRAILER DOWNLOAD :: ERROR :: Skipping...
10 of 1040 :: Die Hard :: 2 of 3 :: Trailer :: Die Hard (1988) Trailer
10 of 1040 :: Die Hard :: 2 of 3 :: trailer :: Die Hard (1988) Trailer :: Sending Trailer link to youtube-dl...
=======================START YOUTUBE-DL=========================
ERROR: fixed output name but more than one file to download
========================STOP YOUTUBE-DL=========================
10 of 1040 :: Die Hard :: 2 of 3 :: trailer :: Die Hard (1988) Trailer :: TRAILER DOWNLOAD :: ERROR :: Skipping...
10 of 1040 :: Die Hard :: 0 Extras Downloaded!
11 of 1040 :: Le Mans
11 of 1040 :: Le Mans :: Searching for "en" extras...
11 of 1040 :: Le Mans :: 2 Extras Found!
11 of 1040 :: Le Mans :: 1 of 2 :: Trailer :: Le Mans (1971) ORIGINAL TRAILER [HD 1080p]
11 of 1040 :: Le Mans :: 1 of 2 :: trailer :: Le Mans (1971) ORIGINAL TRAILER [HD 1080p] :: Sending Trailer link to youtube-dl...
=======================START YOUTUBE-DL=========================
ERROR: fixed output name but more than one file to download
========================STOP YOUTUBE-DL=========================
11 of 1040 :: Le Mans :: 1 of 2 :: trailer :: Le Mans (1971) ORIGINAL TRAILER [HD 1080p] :: TRAILER DOWNLOAD :: ERROR :: Skipping...
11 of 1040 :: Le Mans :: 0 Extras Downloaded!
12 of 1040 :: Grand Prix
12 of 1040 :: Grand Prix :: Searching for "en" extras...
12 of 1040 :: Grand Prix :: 1 Extras Found!
12 of 1040 :: Grand Prix :: 1 of 1 :: Trailer :: Grand Prix - Trailer
12 of 1040 :: Grand Prix :: 1 of 1 :: trailer :: Grand Prix - Trailer :: Sending Trailer link to youtube-dl...
=======================START YOUTUBE-DL=========================
ERROR: fixed output name but more than one file to download
========================STOP YOUTUBE-DL=========================
12 of 1040 :: Grand Prix :: 1 of 1 :: trailer :: Grand Prix - Trailer :: TRAILER DOWNLOAD :: ERROR :: Skipping...
12 of 1040 :: Grand Prix :: 0 Extras Downloaded!`

Radarr docker-compose:
`  radarr:
    image: ghcr.io/linuxserver/radarr:develop
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - type: volume
        source: radarr_config
        target: /config
        volume:
          nocopy: true
      - /mnt/multimedia:/movies  <-- this is directly mapped with fstab in the virtual machine
      - type: volume
        source: download_volume
        target: /downloads
        volume:
          nocopy: true
    ports:
      - 7878:7878
    restart: unless-stopped`

AMTD docker-compose:
`  amtd:
    image: randomninjaatk/amtd
    container_name: amtd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - SCRIPTINTERVAL=2h
      - RadarrUrl=http://192.168.3.50:7878
      - RadarrAPIkey=eb2cc5cca04e44c69667e78b6b3bb5de
      - extrastype=trailers
      - LANGUAGES=en
      - USEFOLDERS=false
      - PREFER_EXISTING=true
      - SINGLETRAILER=true
      - videoformat="--format bestvideo[vcodec*=avc1]+bestaudio"
      - FilePermissions=644
      - FolderPermissions=755
      - AUTOSTART=true
    volumes:
      - type: volume
        source: amtd_config
        target: /config
        volume:
          nocopy: true
      - /mnt/multimedia:/movies <-- this is directly mapped with fstab in the virtual machine
      - type: volume
        source: download_volume
        target: /downloads
        volume:
          nocopy: true
    restart: unless-stopped`

**Comment by TR7Mike** [comment]
Any help at all on what to try or look for?

**Comment by RandomNinjaAtk** [comment]
Remove the quotes for this setting: videoformat

**Comment by TR7Mike** [comment]
Bingo, thanks. 

Not that it's important, but out of curiosity, your docs have it with quotes, is there a reason why on my config it wasn't working?

**Comment by RandomNinjaAtk** [comment]
Bug in the documentation

**Comment by TR7Mike** [comment]
Ok, ta.
