### ISSUE TITLE
Requires Radarr to also be run in Docker?  Issue finding movie paths when Radarr installed on Windows.

### ISSUE THREAD

**Issue by mccune68** [RandomNinjaAtk/docker-amtd#33]
I used to run Radarr in a Docker container, but have been moving apps off of Docker as mine has become a little flaky and crashing often.  When I was running Radarr in Docker, AMTD worked well.  Now, with Radarr installed in Windows, I get "ERROR: Movie Path does not exist, Skipping..." for every movie.  I believe the issue is the volume mapping.

Previously, my Radarr and AMTD Docker commands had this volume mapping defined:

`-v /host_mnt/d/Videos/Movies:/media`

Now, with Radarr just living on Windows, I am not mapping anything.  My movie paths as returned by the Radarr API are their literal windows paths, like:

`D:\\Videos\\Movies\\Lucky (2020)`

This path is fine in Windows-based Radarr, but AMTD can't apparently find it.  I tried the following volume mapping in AMTD, but it's not working either:

`-v /host_mnt/d/Videos/Movies://d/Videos/Movies`

When I set AMTD up this way, and I open a CLI on the container, I can browse to the //d/Videos/Movies path, do an 'ls' command, and it does list all of my movie folders.  Am I setting up this volume path wrong, or is this designed under the assumption that Radarr is also running on Docker?

**Comment by RandomNinjaAtk** [comment]
The current implementation only supports Radarr in a docker container
