### ISSUE TITLE
Kodi needs [existingfilename]-trailer.mkv instead of sanitized name

### ISSUE THREAD

**Issue by guido1981** [RandomNinjaAtk/docker-amtd#35]
Hi,

Can you please add an option to save the trailers as [existingmoviefilename]-trailer.mkv instead of the sanitized name.
Kodi requires this to be able to play them from the UI.
The filename can be easily retrieved from the radarrmoviedata.
I've already made the adjustments myself here, but its not behind some nice option yet, and only for singletrailer.

https://github.com/guido1981/docker-amtd/commits?author=guido1981

**Comment by dedors** [comment]
I have the same problem that I can't play the trailers on kodi.

As additional info, the trailer can also just be named "movie-trailer.mkv" (assuming you have a folder for each movie)

If anyone wants a quick windows workaround: PowerRename (MS Powertoys) search for `.+?(?=-trailer)` replace with _movie_ does the job.

**Comment by RandomNinjaAtk** [comment]
I’ll work on adding this to radarr-extend

Seems like movie-trailer.mkv would be the best method

https://github.com/RandomNinjaAtk/docker-radarr-extended
