### ISSUE TITLE
Trailers folder rename

### ISSUE THREAD

**Issue by PierreDurrr** [RandomNinjaAtk/docker-amtd#36]
Is it possible to change "Trailers" folder with whatever we want ?
Any setting for this, or is it planned ? Or maybe not ?

**Comment by RandomNinjaAtk** [comment]
What would you need to change it to?
It is not planned... and unsure of why that would be needed...

**Comment by PierreDurrr** [comment]
No worry if not planned or worked on...
It could be renamed to i.e. Extras or any other value

Le mer. 22 déc. 2021 à 11:27, RandomNinjaAtk ***@***.***> a
écrit :
