### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by Mansour-J** [RandomNinjaAtk/docker-amtd#37]
Hi, 

My current set up is on a windows machine and I keep getting the following error: 
```
1 of 721 :: <movie_name>:: ERROR: Movie Path does not exist, Skipping...
```

I suspect the issue is the in-compatibility of the windows and Linux path systems. My Radarr application(which is running in the windows) sends the movie file paths with the windows folder structure path and the script tries to address them and it doesn't find them and it gets confused. 

In the document it mentions that the volume paths should be the same, but due to the windows vs liunux path system, I couldn't get it exactly the same: This is how I run the docker file:
```bash
# Running below command would fail
$ docker create \
   --name=amtd \
   -v E\:\\first_folder\\second_folder\\movie_folder://E\://first_folder//second_folder//movie_folder \

> Error response from daemon: invalid mode: //poseidon-backup//video//movies



# Below runs successfully but ends up with the minor path discrepancy and issues
docker create \
  -v E\:\\first_folder\\second_folder\\movie_folder://E//first_folder//second_folder//movie_folder \
```

**Comment by RandomNinjaAtk** [comment]
Both applications need to be in docker containers.
