### ISSUE TITLE
Switch to yt-dlp planned? Downloads are painfully slow

### ISSUE THREAD

**Issue by kamtschatka** [RandomNinjaAtk/docker-amtd#38]
I am using amtd and I have noticed that it seems to get stuck. After looking at the temp folder, I noticed, that the file is growing steadily, but it is incredibly slow.
It is at about 50kb/s, while I have a 100Mbit connection and that should definitely go faster.

I am also running youtube-dl as well and noticed the same thing there as well, so I did some searching and as it turns out that yt-dl is being throttled (also check https://www.reddit.com/r/youtubedl/comments/q6r74m/youtubecom_downloads_with_youtubedl_are_slow/)

Are there any plans to switch to yt-dlp, which seems to be unaffected by this?

**Comment by kamtschatka** [comment]
I found some more information: https://github.com/ytdl-org/youtube-dl/pull/30184
Seems like an update might already solve the problem?

**Comment by ookla-ariel-ride** [comment]
youtube-dl is no longer being updated.  yt-dlp is the successor it seems.

**Comment by RandomNinjaAtk** [comment]
The latest image should be building with the update to swap to yt-dlp. Please give it a try and report back...
