### ISSUE TITLE
Feature Request: more companion like (UI, more options)

### ISSUE THREAD

**Issue by snickers2k** [RandomNinjaAtk/docker-amtd#39]
Already love this app. works great. thanks for that.

But although this is a huge request, i'd really wish to see this a real companion app like bazaar does it for subtitles for example.
Because i think Trailers are such an important thing, we need an even more versatile app with UI and more options ^^

- upgrade functionality, with quality threshold to stop upgrading
    - allow qualities=720p,1080p,2160p
    - prefer qualities=1080p
    - upgrade until quality=XY
    - upgrade until language=XY
- ffprobe to check the actual quality and language (if not already)
- history and wanted
- scheduler
- different options for trailers and extras 
    - trailer=german only, 1080p
    - extras=de,en , 720p)
- movie support
- series support
   - per season
- extras support
- New Movies (not in Library) for pre-rolls
- **Providers** (youtube, trailers.apple.com, imdb, themoviedb, moviepilot(german), traileraddict, and probably more)
- regexp Filtering (must contain / must not contain -- e.g. block certain youtube-channels (for the ones with own preroll)
- subtitles (yes/no=remove/seperate=extract)
- (fancy): tags from sonarr/radarr to automate options for certain movies
- (fancy): "inject specials" to certain tags
    - tag: jacky-chan="10 Scenes Jacky Chan almost died"(https://www.youtube.com/watch?v=RKRUYJarcEk)

maybe even partner with or fork some parts of https://github.com/cgnetwork/trailarr or https://github.com/taylorbobaylor/TrailerDownloader as those two seem to be more the UI related apps with less features and no sonarr/radarr implementation

(https://github.com/cgnetwork/trailarr/issues/10)

of course maybe you don't want to go that route, but just asking ... :)

thanks

**Comment by RandomNinjaAtk** [comment]
No, this will likely not happen
