### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by wildsavage** [RandomNinjaAtk/docker-amtd#4]
Getting the following error running against the preview version of Radarr

######################################### DOWNLOADING TRAILERS #########################################
find: ‘’: No such file or directory
########################################### SCRIPT COMPLETE ############################################

Assuming this was built to run against V2 but wanted to confirm

**Comment by RandomNinjaAtk** [comment]
I've only tested on Aphrodite. Your volume mappings are probably wrong. Replicate the radarr volume mappings 1:1 to this container (excluding the config volume) 

And that will probably resolve your issue

**Comment by wildsavage** [comment]
I got caught with my goofy unraid / docker networking setup. the app works well, the issue was me, my bad!
