### ISSUE TITLE
Possible to download extras with '*'/wildcard languages?

### ISSUE THREAD

**Issue by xthursdayx** [RandomNinjaAtk/docker-amtd#40]
In cases when extras and trailers cannot be found in the selected `LANGUAGES`, is it possible to download trailers and extras in any available language (using * as a wildcard, for example)?

My `LANGUAGES` and `subtitlelanguage` are set to `en`, but I have many non-English movies for which no English-language trailer or extras can be found. Is it possible to add `-e LANGUAGES=en,*` to allow for non-English language extras and trailer to be downloaded, and, if so, is it possible to tell AMTD to only download non-English extras if they have subtitles?

Thanks!

**Comment by RandomNinjaAtk** [comment]
No, don't think so and its not currently supported in the new project radarr-extended (https://github.com/RandomNinjaAtk/docker-radarr-extended)
