### ISSUE TITLE
Bug: wrong trailer

### ISSUE THREAD

**Issue by snickers2k** [RandomNinjaAtk/docker-amtd#41]
instead of trailer for "the kid detective" amtd just downloaded this one: 
https://www.youtube.com/watch?v=QTgntn1JUJ4
trailer for "THE KID 2019"

please make sure to only download a full matching regexp to avoid wrong trailers from similar named movies.
wrong trailers are the worst case... even worse than having no trailer at all.

**Comment by RandomNinjaAtk** [comment]
The trailers list comes from https://www.themoviedb.org/

No searching or regex being performed, the only way to fix it, would be to update themoviedb.org with the correct information.
