### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by saschabrockel** [RandomNinjaAtk/docker-amtd#43]
Any chances on ARM support? Is there anything planned?

**Comment by saschabrockel** [comment]
I have tried it myself. So your Dockerfile works as it is for arm64 (what I need and I guess the most other people that don't need amd64). For arm/v7 it crashes with the following error:

`ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f2bz7u_1/brotli/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f2bz7u_1/brotli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bz26owce/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/brotli Check the logs for full command output.`

So you are also able to build the image for arm64 at least. Would you be so kind to do this? I don't know how you build the docker images but the command `docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag RandomNinjaAtk/docker-amtd:latest.` would do it for you.

**Comment by RandomNinjaAtk** [comment]
radarr-extended will support arm platforms: https://github.com/RandomNinjaAtk/docker-radarr-extended

**Comment by saschabrockel** [comment]
Wait what is radarr extended now?
