### ISSUE TITLE
Bug: amtd cannot communicate with latest version of Radar 4.0.4.5922

### ISSUE THREAD

**Issue by michpas** [RandomNinjaAtk/docker-amtd#44]
I updated radar to 4.0.4.5922 (in linuxserver docker)
Since that update, the amtd script -which worked for 6 months perfectly fine- stopped working.
Updated amtd (ilarramendi/better-covers:latest) to latest version
Issue/error is the same. Log below
**Key errors seem to be : Cannot communicate with Radarr, no response.**

Reading Radarr update log: https://www.reddit.com/r/radarr/comments/rvb52f/new_release_radarr_v4005745_develop/
it states:

**Radarr Breaking API Changes
Radarr v4 no longer supports the legacy (v0.2) API
Native ASPCore API Controllers (stricter typing and other small API changes)**

Could it be that the API that amtd uses no longer works on Radar v4+

`############################################ Automated Movie Trailer Downloader (AMTD)
############################################ CONFIGURATION VERIFICATION
AMTD Script Autostart: DISABLED
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
ERROR: Cannot communicate with Radarr, no response
ERROR: URL: http://192.168.0.170:8310/
ERROR: API Key: [masked]
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
Radarr: Verifying Movie Directory Access:
Radarr Extras Selection: trailers
Radarr Extras Audio Languages: nl,en (first one found is used)
Radarr Extras Format Set To: --format bestvideo[vcodec*=avc1]+bestaudio
Radarr Extras Subtitle Language: nl,en
Radarr Extras File Permissions: 777
Radarr Extras Foldder Permissions: 755
Radarr Single Trailer: ENABLED
Radarr Use Extras Folders: DISABLED
WARNING: PREFER_EXISTING not set, using default...
Prefer Existing Trailer: DISABLED
ERROR :: Exiting...
[cmd] /bin/bash exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by RandomNinjaAtk** [comment]
Looks like your amtd container is not fully up-to-date and your linuxserver radarr app is not the latest version.

You need to update your containers/app and try again...

**Comment by michpas** [comment]
Hi. Thanks for your quick comments. I'm still not sure where I''m doing wrong.
Have now completely rebuild the amtd container. 
The radarr verion is also actual:

Radarr Version: 4.0.4.5922
Package Version: 4.0.4.5922-ls129 by linuxserver.io
Docker:Yes

I'm still getting the same error:

Any suggestions on how to solve?

############################################ Automated Movie Trailer Downloader (AMTD)
############################################ SCRIPT VERSION 1.2.81
############################################ DOCKER VERSION 1.0.8
############################################ CONFIGURATION VERIFICATION
AMTD Script Autostart: ENABLED
WARNING: AMTD Script Interval not set! Using default...
AMTD Script Interval: 15m
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
ERROR: Cannot communicate with Radarr, no response
ERROR: URL: http://192.168.0.170:8310/
ERROR: API Key: [masked]
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
Radarr: Verifying Movie Directory Access:

**Comment by RandomNinjaAtk** [comment]
The radarr version I'm using is: 4.0.5.5923-ls234 by linuxserver.io

And I tested it locally with the same docker/script version that you just posted.

**Comment by michpas** [comment]
ah. I tried a few things. Got it back to work.
Sharing the solution: I had radarrUrl in environmental as: http://192.168.0.170:8310/
Removed the last  '/' and now it worked.
Didn't notice this. This was all working fine on previous radarr version; but in these new versions no longer.
Thanks again ! Great tool.
