### ISSUE TITLE
Cannot comunicate with radarr

### ISSUE THREAD

**Issue by memnos** [RandomNinjaAtk/docker-amtd#45]
Hello, i've just installed docker with this script:
`docker create \
  --name=amtd \
  -v /opt/AMTD/config:/config \
  -v /media/google_crypt/crypt/Movies:/media/google_crypt/crypt/Movies \
  -e PUID=1000 \
  -e PGID=1000 \
  -e AUTOSTART=true \
  -e SCRIPTINTERVAL=1h \
  -e extrastype=trailers \
  -e LANGUAGES=it,en \
  -e videoformat="--format bestvideo[vcodec*=avc1]+bestaudio" \
  -e subtitlelanguage=it \
  -e USEFOLDERS=false \
  -e EndClient=emby \
  -e SINGLETRAILER=true \
  -e PREFER_EXISTING=true \
  -e FilePermissions=644 \
  -e FolderPermissions=755 \
  -e RadarrUrl=http://*.*.*.*:* \
  -e RadarrAPIkey=*************************** \
  --restart unless-stopped \
  randomninjaatk/amtd

`
but when start with:
docker exec -it amtd /bin/bash -c 'bash /config/scripts/download.bash'

I have this error:
https://pastebin.com/2mT1H8sK

Whan am i doing wrong?

**Comment by memnos** [comment]
Radarr version is 4.0.4.5922

**Comment by RandomNinjaAtk** [comment]
https://github.com/RandomNinjaAtk/docker-amtd/issues/44

**Comment by memnos** [comment]
I didn't understand exactly how to solve.
I updated ATMD
############################################ Automated Movie Trailer Downloader (AMTD)
############################################ SCRIPT VERSION 1.2.81
############################################ DOCKER VERSION 1.0.8
############################################ CONFIGURATION VERIFICATION

I updated radarr at version 4.0.5.5923

But errore is the same.

I dont have the / at the end of radarr  URL: http://*.*.*.*:*

DO i miss something?

**Comment by RandomNinjaAtk** [comment]
Try removing this setting: -e videoformat="--format bestvideo[vcodec*=avc1]+bestaudio"

**Comment by RandomNinjaAtk** [comment]
What are you using for the url?
If your trying to use localhost or 127.0.0.1, that is probably why it is failing... You need to use the same URL that you would use in your browser to access it.

**Comment by memnos** [comment]
Yes i use the url to enter from remote http://5.*.*.* on my browser. 
My radarr and ATMD scripts are on a vps so i donw use localhost or 127.0.0.1

**Comment by RandomNinjaAtk** [comment]
You should double check your api key then. Or generate a new api key and try again. Its a problem with your configuration somewhere... so you have to try all the things to solve it... nothing to be done on this end...

**Comment by memnos** [comment]
I tried to renew api, but nothing. I really don't know what else to check.
Isn't there a way to have a more verbose log to see whats wrong?

**Comment by RandomNinjaAtk** [comment]
You could enable verbose logging in radarr and see if can see the api call for any errors.

You could also try extracting the url from the curl commands from these lines, and running the url in the browser with the variables replaced with your info to see what is reported back...
https://github.com/RandomNinjaAtk/docker-amtd/blob/77848fb410c93c8616cc312aab28e4514e905d63/root/scripts/download.bash#L31-L32

**Comment by memnos** [comment]
If i run the curl command from the first line a have no answer.
With the second line i see this:
 "appName": "Radarr",
  "version": "4.0.5.5923",
  "buildTime": "2022-02-11T14:36:47Z",
  "isDebug": false,
  "isProduction": true,
  "isAdmin": false,
  "isUserInteractive": true,
  "startupPath": "/opt/Radarr",
  "appData": "/root/.config/Radarr",
  "osName": "ubuntu",
  "osVersion": "16.04",
  "isNetCore": true,
  "isLinux": true,
  "isOsx": false,
  "isWindows": false,
  "isDocker": false,
  "mode": "console",
  "branch": "master",
  "authentication": "forms",
  "sqliteVersion": "3.11.0",
  "migrationVersion": 206,
  "urlBase": "",
  "runtimeVersion": "6.0.1",
  "runtimeName": "netCore",
  "startTime": "2022-02-11T14:39:02Z",
  "packageUpdateMechanism": "builtIn"

**Comment by memnos** [comment]
I found out what the problem was.
My firewall blocked my calls from inside.
Disabling firewall all is ok.
Sorry, my fault.
You can close issue.
