### ISSUE TITLE
EndClient information

### ISSUE THREAD

**Issue by memnos** [RandomNinjaAtk/docker-amtd#46]
I would like to have informations about EndClient option.
What does change from a client to another?
Naming? In this case, what does it change?
Tnx

**Comment by RandomNinjaAtk** [comment]
Folder naming, it's designed to make the files more compatible with the desired endclient...

**Comment by memnos** [comment]
Is there the possibility to name the trailer MOVIEFILENAME-trailer.EXT?

**Comment by RandomNinjaAtk** [comment]
radarr-extended should support this by having movie-trailer.mkv as the file name for Kodi compatiblity.
https://github.com/RandomNinjaAtk/docker-radarr-extended
