### ISSUE TITLE
Request/Question: Refresh metadata in plex so trailers show up

### ISSUE THREAD

**Issue by asherbig** [RandomNinjaAtk/docker-amtd#49]
When trailers are downloaded, I've noticed that the trailers don't appear in plex until I manually "refresh metadata" for the movie. I have `Scan my library automatically` and `Run a partial scan when changes are detected` checked but it doesn't seem to pick up the trailers.

Could amtd connect to plex with a webhook similar to how radarr can make a callout to plex? Or is there a setting that I'm missing that would fix this already?

**Comment by RandomNinjaAtk** [comment]
This will be improved in radarr-extended (https://github.com/RandomNinjaAtk/docker-radarr-extended)
