### ISSUE TITLE
YouTube DL needs update.

### ISSUE THREAD

**Issue by xdtrammell** [RandomNinjaAtk/docker-amtd#6]
How can you update the youtube-dl in the container, I tried to run youtube-dl U in the bash shell of the docker container but it says python does not exist.
![chrome_t4pO0Z84IL](https://user-images.githubusercontent.com/3378289/90393904-9f754880-e05f-11ea-924e-d1afd85fea7b.png)

**Comment by RandomNinjaAtk** [comment]
No, it does not need an update, you need to use cookies.txt

See the cookies directory: https://github.com/RandomNinjaAtk/docker-amtd#directories

**Comment by RandomNinjaAtk** [comment]
I assume this is resolved, re-open if needed
