### ISSUE TITLE
language

### ISSUE THREAD

**Issue by foXaCe** [RandomNinjaAtk/docker-amtd#7]
I think I must have missed something. I add "fr" and it downloads all the trailers in English.

**Comment by RandomNinjaAtk** [comment]
My only question would be, are you sure the trailers that are available actually have "fr" as an available option? 

You should look into a few of them to see if that is an option at all directly on youtubes site. If it isn't maybe that is why...

Edit:

I've also never tried any other language, so it may just not work.... But my suspicion is most trailers are in English only...

**Comment by foXaCe** [comment]
https://www.youtube.com/watch?v=AzWSHM9rYCo

**Comment by foXaCe** [comment]
and it downlad english version

**Comment by RandomNinjaAtk** [comment]
So after some further review, the language setting only applies to subtitles, there is no code at all to select the audio language. If I had to take a guess, you most likely have to control the langauge using the video format option, which controls audio selection:

https://github.com/RandomNinjaAtk/docker-amtd#parameters

Which is not very simple to handle. You may need to look at youtube-dl documentation and expirement to get it to work:
https://github.com/ytdl-org/youtube-dl#video-format-options

It's not something I'm that familiar with.

Also funny enough, the country code setting isn't actually used for anything that I can tell. Might just be legacy code that got moved into the script, when I copied stuff out of other scripts I wrote and accidentally inserted it here improperly...

If you find a format option that works for it, I may somehow be able to script the selection in. But you'd need to provide an example.

**Comment by foXaCe** [comment]
can be done a search:
movie_name +"french"

**Comment by RandomNinjaAtk** [comment]
This script doesn't use search, Radarr provides a linked youtube trailer id for most movies, this script simply just downloads the linked youtube id. So it would only work if the linked video has more then one language attached, and you can somehow select it using youtube-dl (probably through the audio/video format selection option...)

**Comment by foXaCe** [comment]
ok so radarr should point to a link on a trailer in the correct language

**Comment by RandomNinjaAtk** [comment]
Yeah, I'm not sure this is possible with youtube-dl itself. You may need to add a feature request to radarr, for it to include multiple trailer id's in multiple languages. I could then use that pull the desired trailer based on language preference. Right now Radarr only provides a single ID for a particular movie, and they're probably all english...

**Comment by foXaCe** [comment]
I think my level of English and my knowledge are too low for that

**Comment by RandomNinjaAtk** [comment]
You would request it on their repo by posting an issue as a feature request, or try the discord channel: https://github.com/Radarr/Radarr/

**Comment by foXaCe** [comment]
https://discordapp.com/channels/264387956343570434/633193129515810816/745012413220520047

**Comment by RandomNinjaAtk** [comment]
@foXaCe I may have an update shortly that will enable languages based on the subtitle language selection... I'm doing some testing of it now.

**Comment by RandomNinjaAtk** [comment]
@foXaCe If you switch to the "themoviedb" image tag, you can try the new features...

https://github.com/RandomNinjaAtk/docker-amtd/tree/themoviedb

`docker pull randomninjaatk/amtd:themoviedb`

Image is still building at the moment, wait for it to hit docker hub before switching...

Edit: Image is up!

**Comment by foXaCe** [comment]
ok i will test when i get home from work

Le mar. 18 août 2020 à 14:23, RandomNinjaAtk <notifications@github.com> a
écrit :

**Comment by foXaCe** [comment]
themoviedb version support more language ?

**Comment by RandomNinjaAtk** [comment]
In theory it should, not tested though. If there isn't a trailer in your desired set language, I believe right now, you won't get anything...

Edit: Had to push a small bugfix, it should now be downloading via specified language. https://github.com/RandomNinjaAtk/docker-amtd/commit/8b7a6bf3c3268a15b9ea94f6e1f50df1ec7ea65f

Again, if nothing is available in your language, then you won't get anything... I have not actually tested this, so report back after you do. Image update should be building with the change...

**Comment by RandomNinjaAtk** [comment]
@foXaCe Quick update, this should now be resolved. I've merged this back to mainline. Please update to the normal version when its available and test accordingly...

**Comment by foXaCe** [comment]
ok thank you
it work very good
it download trailers in my language
good job thank you
