### ISSUE TITLE
No Trailer ID Found, Skipping

### ISSUE THREAD

**Issue by Tomcatter31** [RandomNinjaAtk/docker-amtd#9]
I have managed to get my script setup, however the log file is showing:

```log
26 of 1126 :: Anthropoid
26 of 1126 :: Anthropoid :: ERROR: No Trailer ID Found (Anthropoid), Skipping...
```

Do the movies need to be named a specific way, currently the name is:

Movie name - Release year

I have changed it to

Movie name - (Release year) - IMDB ID

**Comment by RandomNinjaAtk** [comment]
If you have the latest update, that means https://www.themoviedb.org does not have any videos for that movie based on your settings. Verify on that website if any videos are listed, if none, you need to add it there.

Edit: The Subtitle language setting does effect the results. So it's possible there are videos available but not
in your desired language, which would also cause that error.

**Comment by Tomcatter31** [comment]
This is happening on all of the movies I have downloaded, language is set to English

**Comment by RandomNinjaAtk** [comment]
So your subtitle setting is set to
 ```
en
``` 
?

**Comment by Tomcatter31** [comment]
![image](https://user-images.githubusercontent.com/57972309/90569777-74344b80-e17c-11ea-9d35-1e63d63b5575.png)

**Comment by Tomcatter31** [comment]
![image](https://user-images.githubusercontent.com/57972309/90569870-a2199000-e17c-11ea-860b-747076f42194.png)

**Comment by Tomcatter31** [comment]
Think i see the issue - capitlized T on "Trailers"

**Comment by Tomcatter31** [comment]
ok, that didnt work, seems "all" works but not trailers.

**Comment by RandomNinjaAtk** [comment]
Looks right, make sure there are no spaces before or after the setting. That can break it.

Also double check a couple videos to make sure they should be available. This script only pulls from YouTube as a source so if a trailer is there but not on YouTube it will skip those

**Comment by Tomcatter31** [comment]
No spaces at all

Confirmed - "all" settings work, but not trailers only-

![image](https://user-images.githubusercontent.com/57972309/90570196-3683f280-e17d-11ea-84c0-881d938a78d0.png)

**Comment by Tomcatter31** [comment]
would like to get the trailer only working as having everything download will eat space on my NAS

**Comment by RandomNinjaAtk** [comment]
Could just be a bug, can't say I tested that, but it should have worked. I'll look into when I get a chance.

Keep in mind, when it is working as set to trailers, you could end up downloading multiple trailers, because it's only being restricted to videos marked as trailers

**Comment by Tomcatter31** [comment]
Thanks

**Comment by RandomNinjaAtk** [comment]
@Tomcatter31 It should be fixed now, check for updates in the next 10-15 minutes for an image update that has the latest code. Should be on version 1.0.5

Let me know if that fixes it...

**Comment by RandomNinjaAtk** [comment]
@Tomcatter31 Update should be available now!

**Comment by Tomcatter31** [comment]
All good and working now... Thank you
